### PR TITLE
Fix full framework benchmarks

### LINKED ISSUE #306: Fix failing Full Framework benchmarks
```log
// **************************
// Benchmark: CscBench.CompileTest: Job-NTJWUA(Runtime=Clr, Toolchain=net461, InvocationCount=1, IterationCount=1, IterationTime=250.0000 ms, MaxIterationCount=20, MinIterationCount=15, RunStrategy=ColdStart, UnrollFactor=1, WarmupCount=0)
// *** Execute ***
// Launch: 1 / 1
// Execute: C:\dotnetbuild\work\7a199420-a4e1-426a-b57d-b16f6df9bc0b\Work\8f92afe2-e998-4463-ad2f-f66c3a573f12\Exec\bin\Release\net461\37a15f28-25c4-4e5d-b338-49eaffa542f0\bin\Release\net461\37a15f28-25c4-4e5d-b338-49eaffa542f0.exe --benchmarkName "CscBench.CompileTest" --job "Runtime=Clr, Toolchain=net461, InvocationCoun
// BeforeAnythingElse

// Benchmark Process Environment Information:
// Runtime=.NET Framework 4.7.2 (CLR 4.0.30319.42000), 64bit RyuJIT-v4.7.3132.0
// GC=Concurrent Workstation
// Job: Job-IPPFVK(Runtime=Clr, InvocationCount=1, IterationCount=1, IterationTime=250.0000 ms, MaxIterationCount=20, MinIterationCount=15, RunStrategy=ColdStart, UnrollFactor=1, WarmupCount=0)


System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: fileName
   at System.IO.FileInfo..ctor(String fileName)
   at CscBench.SetMscorlib() in C:\dotnetbuild\work\7a199420-a4e1-426a-b57d-b16f6df9bc0b\Work\8f92afe2-e998-4463-ad2f-f66c3a573f12\Exec\coreclr\Roslyn\CscBench.cs:line 37
   at BenchmarkDotNet.Engines.EngineFactory.CreateReadyToRun(EngineParameters engineParameters)
   at BenchmarkDotNet.Autogenerated.Runnable_17.Run(IHost host, String benchmarkName) in C:\dotnetbuild\work\7a199420-a4e1-426a-b57d-b16f6df9bc0b\Work\8f92afe2-e998-4463-ad2f-f66c3a573f12\Exec\bin\Release\net461\37a15f28-25c4-4e5d-b338-49eaffa542f0\37a15f28-25c4-4e5d-b338-49eaffa542f0.notcs:line 9933
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BenchmarkDotNet.Autogenerated.UniqueProgramName.AfterAssemblyLoadingAttached(String[] args) in C:\dotnetbuild\work\7a199420-a4e1-426a-b57d-b16f6df9bc0b\Work\8f92afe2-e998-4463-ad2f-f66c3a573f12\Exec\bin\Release\net461\37a15f28-25c4-4e5d-b338-49eaffa542f0\37a15f28-25c4-4e5d-b338-49eaffa542f0.notcs:line 766
// AfterAll
ExitCode != 0
No more Benchmark runs will be launched as NO measurements were obtained from the previous run!

```

### PR DESCRIPTION
**Pull request by adamsitnik**
Fixes #306

### CODE REVIEW

File: src/benchmarks/micro/corefx/System.Diagnostics/Perf_Process.cs [hunk 1]
```diff
@@ -22,13 +22,6 @@ public class Perf_Process
         [Benchmark]
         public void GetProcessById() => Process.GetProcessById(_currentProcessId).Dispose();
 
-        [Benchmark]
-        public void EnterLeaveDebugMode()
```
Comment (adamsitnik) [inline src/benchmarks/micro/corefx/System.Diagnostics/Perf_Process.cs]: @jorive @billwert I am removing this benchmark because:

1. it does nothing on Unix OSes (not implemented in CoreCLR, instead of throwing does nothing)
2. On Windows it requires some certain privileges to work, it currently fails even on my box (it used to work fine)

I am the person who created this benchmark ;)

File: src/benchmarks/micro/corefx/System.Diagnostics/Perf_Process.cs [hunk 2]
```diff
@@ -46,41 +39,5 @@ public void GetProcessesByName()
                 process.Dispose();
             }
         }
-        
-        [Benchmark]
-        public void StartAndWaitForExitDotNetVersion()
```
Comment (adamsitnik) [inline src/benchmarks/micro/corefx/System.Diagnostics/Perf_Process.cs]: @jorive @billwert again I am the person who created this benchmark... So the goal here was to have something that mimics a simple "Hello World" process startup time benchmark. But it turned out to be an unstable benchmark.

Since we are soon going to introduce Scenarios with proper process startup time benchmarks I am going to remove this benchmark now

**Comment by adamsitnik** [comment]
It fixed the Full Framework benchmark issues, I am merging it now because it's blocking me.
